### ISSUE TITLE
failed to load resource: the server responded with a status of 404 (not found)

### ISSUE THREAD

**Issue by Harddisx** [respectZ/blue-archive-spine#1]
Sir I got this error . this is not import animetion skle.file . thank in advance
![image](https://user-images.githubusercontent.com/50569620/150570378-29342fa3-100c-43c0-913d-703785226977.png)
![image](https://user-images.githubusercontent.com/50569620/150570603-a61730d3-2879-449c-bab9-0aa3bc4facf8.png)

**Comment by respectZ** [comment]
As it says
Make sure the path is correct and exists

**Comment by Harddisx** [comment]
Oh my bad . I found it . thank sir
