### ISSUE TITLE
Character adding

### ISSUE THREAD

**Issue by QBASpriteFinder** [respectZ/blue-archive-spine#17]
I was wondering If you could add Hayase Yuuka in her gym out for me? It would really appreciate it.

**Comment by SunsetMkt** [comment]
Hayase Yuuka Gym version is currently only on Japan version. It's model name is `ch0184`.

https://github.com/lwd-temp/blue-archive-spine-production/blob/jp/assets/spine/ch0184_spr/CH0184_spr.png

**Comment by QBASpriteFinder** [comment]
Thanks!
