### ISSUE TITLE
index.html do not work

### ISSUE THREAD

**Issue by maromameta** [respectZ/blue-archive-spine#22]
I downloaded the file with the resources and ran index.html, but I cannot select the spine with this screen..

![2023y01m26d_232808863](https://user-images.githubusercontent.com/10674115/214863579-a6714d63-5054-47be-9caf-c13f01a54f78.jpg)

I don't know much about it, so I don't have much information, but do you know what the problem is?

**Comment by respectZ** [comment]
Most likely problem with json data didn't load correctly
Did you run it through webserver?

**Comment by maromameta** [comment]
Does .json mean this skeleton file?
![2023y01m27d_172243924](https://user-images.githubusercontent.com/10674115/215041543-3bc45a25-3b43-4a71-9958-bd3ef232fdf3.jpg)
It is garbled, is it ok?
(I am Japanese and the character encoding of this file seems to be ANSI)
![2023y01m27d_172254698](https://user-images.githubusercontent.com/10674115/215041584-ab683815-98c4-4054-8368-936dca62a167.jpg)

I opened the index.html file locally.(just double click the file)

**Comment by respectZ** [comment]
Oh, you can't run it by opening index.html directly
Run it through web server, like xampp will do

**Comment by maromameta** [comment]
oh!
I got it.
![2023y01m27d_181029775](https://user-images.githubusercontent.com/10674115/215049825-d6049ef9-a850-4d8d-9119-1c5606c7a07e.jpg)
I'm sorry for troubling you. Thanks!
