### ISSUE TITLE
Saving big without background

### ISSUE THREAD

**Issue by sanskar-mk2** [respectZ/blue-archive-spine#23]
Hello, I have gotten different pose from the dropdown.
I then download it.
But then there is problem that I can only download the frame size of my browser, so I am unable to get better resolution.
And another problem is that there is background of black color, so I have to run my download through the background remover.
I feel that it is possible to grab the pose of bigger quality and without background. Please advise.

**Comment by Poleric** [comment]
This might be late, but if you're trying to save the 2D sprites in png format, you can try running this script in the devtools console
```javascript
function exportImage() {
  function download_sprite_as_png(renderer, sprite, fileName) {
    renderer.extract.canvas(sprite).toBlob(function(b){
      var a = document.createElement('a');
      document.body.append(a);
      a.download = fileName;
      a.href = URL.createObjectURL(b);
      a.click();
      a.remove();
    }, 'image/png');
  }
  let charName = option.models.options[option.models.selectedIndex].text.replace("_home", "")
  download_sprite_as_png(app.renderer, char, `${charName}_${optionAnimations.value}.png`)
};
exportImage()
```
Source: https://www.html5gamedevs.com/topic/31190-saving-pixi-content-to-image/
