### ISSUE TITLE
Sound and Loop could only be played once.

### ISSUE THREAD

**Issue by Ishiharaerika** [respectZ/blue-archive-spine#4]
Hello! How are you doing?
I really like this project of yours. The vividness of the characters in Blue Archive certainly makes the players joyful. However, on the site you made from this source code, there is a problem: any Talk_0? of Talk Sound can only be played once, and switching roles then switching back to that role's Talk_0? still does not play Talk Sound. I've also found the problem after running your source code locally. Is it in the Loop related code? In any case, I would appreciate if you could make a change to the relevant part of the main.js code. No doubt that we'd all be appreciated.

**Comment by respectZ** [comment]
Hey! I'm good
Just checked and found the problem.
The audio needs to be loaded in order to play, so it only trigger once
Gonna fix it

**Comment by Ishiharaerika** [comment]
You're so kind. I'm grateful to hear this!
