### ISSUE TITLE
Unable to Export Animation

### ISSUE THREAD

**Issue by baburu** [respectZ/blue-archive-spine#7]
I tried to export some Idle animation but it won't work

pixi.js:34932          GET https://respectz.github.io/blue-archive-spine/assets/assets/spine/azusa_swimsuit_home/Azusa_swimsuit_home.skel 404
_loadXhr @ pixi.js:34932
load @ pixi.js:34735
(anonymous) @ pixi.js:36207
next @ pixi.js:34047
eachSeries @ pixi.js:34060
_loadResource @ pixi.js:36196
Loader._boundLoadResource @ pixi.js:35706
process @ pixi.js:34139
resume @ pixi.js:34167
load @ pixi.js:36131
exportAnimation @ canvas-exporter.js:20
option.export.onclick @ (index):212
pixi-spine.js:8492 Uncaught Error: The spineData param is required.
    at new Spine (pixi-spine.js:8492:17)
    at canvas-exporter.js:21:30
    at MiniSignal.dispatch (pixi.js:33926:19)
    at Loader._onComplete (pixi.js:36233:22)
    at pixi.js:36271:17
    at next (pixi.js:34047:10)
    at AtlasParser.use (pixi-spine.js:9033:18)
    at pixi.js:36254:11
    at pixi.js:34055:10

**Comment by respectZ** [comment]
Thanks for pointing it out. The issue should be fixed with the latest commit.

**Comment by baburu** [comment]
thanks so much
